- name: Income below 50,000 and Age at or over 55 qualifies
  period: 2021-12-01
  input:
    age: 55 # Defined with the period DAY
    income: # Defined with the period YEAR
      2021: 49999
  output:
    eligible: True
